# Generated by Django 6.0.3 on 2026-03-15 00:53

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'event categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(help_text='Short summary for listing cards.')),
                ('content', tinymce.models.HTMLField(help_text='Full event details (rich text).')),
                ('date', models.DateField(help_text='Event start date.')),
                ('end_date', models.DateField(blank=True, help_text='Optional end date for multi-day events.', null=True)),
                ('time', models.TimeField(help_text='Event start time.')),
                ('location', models.CharField(help_text='Venue or city name.', max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='events/')),
                ('registration_url', models.URLField(blank=True, help_text='External registration link.')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventcategory')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
    ]
