# Generated by Django 6.0.3 on 2026-03-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, unique=True)),
                ('format', models.CharField(choices=[('lecture', 'Lecture'), ('interview', 'Interview'), ('live', 'Live'), ('documentary', 'Documentary'), ('promotional', 'Promotional')], default='lecture', max_length=50)),
                ('language', models.CharField(choices=[('english', 'English'), ('twi', 'Twi')], default='english', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('archive', 'Archive'), ('published', 'Published')], default='pending', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
