# Generated by Django 6.0.3 on 2026-06-28 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, upload_to='teachings/series/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'teaching series',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AlterModelOptions(
            name='teaching',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='teaching',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teaching',
            name='media_file',
            field=models.FileField(blank=True, help_text='Video/audio file hosted on R2.', upload_to='teachings/media/'),
        ),
        migrations.AddField(
            model_name='teaching',
            name='media_kind',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio')], default='video', max_length=10),
        ),
        migrations.AddField(
            model_name='teaching',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order within a series.'),
        ),
        migrations.AddField(
            model_name='teaching',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='teaching',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='teachings/thumbs/'),
        ),
        migrations.AddField(
            model_name='teaching',
            name='tier',
            field=models.CharField(choices=[('general', 'General (open to everyone)'), ('premium', 'Premium (members/students only)')], default='general', max_length=10),
        ),
        migrations.AddField(
            model_name='teaching',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube URL, if hosted on YouTube.'),
        ),
        migrations.AddField(
            model_name='teaching',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachings', to='teachings.teachingseries'),
        ),
    ]
