# Generated by Django 6.0.3 on 2026-09-20 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_contact_centre'),
        ('teachings', '0002_teachingseries_alter_teaching_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaching',
            name='author',
            field=models.CharField(default='Dr. Baffour Jan', help_text='Shown as the teaching attribution in the app.', max_length=255),
        ),
        migrations.AddField(
            model_name='teaching',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Times the teaching was opened in the app.'),
        ),
        migrations.CreateModel(
            name='TeachingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveSmallIntegerField(default=0)),
                ('position_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_progress', to='members.contact')),
                ('teaching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_rows', to='teachings.teaching')),
            ],
            options={
                'verbose_name_plural': 'teaching progress',
                'ordering': ['-last_viewed_at'],
                'constraints': [models.UniqueConstraint(fields=('contact', 'teaching'), name='unique_contact_teaching')],
            },
        ),
    ]
