# Generated by Django 6.0.3 on 2026-09-30 03:43

import django.db.models.deletion
from django.db import migrations, models


def seed_lesson_type(apps, schema_editor):
    """Existing rows only ever described themselves as video or audio.
    Carry that across rather than letting every audio lesson default to
    video and mislabel itself in the app."""
    Teaching = apps.get_model('teachings', 'Teaching')
    Teaching.objects.filter(media_kind='audio').update(lesson_type='audio')
    Teaching.objects.filter(media_kind='video').update(lesson_type='video')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('teachings', '0003_teaching_author_teaching_view_count_teachingprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaching',
            name='downloadable',
            field=models.BooleanField(default=False, help_text='Whether this lesson may be taken offline. Not every lesson can be — licensing and live sessions differ.'),
        ),
        migrations.AddField(
            model_name='teaching',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('written', 'Written'), ('reflection', 'Reflection'), ('practice', 'Practice'), ('quiz', 'Quiz'), ('live', 'Live session'), ('resource', 'Downloadable resource')], default='video', max_length=12),
        ),
        migrations.AddField(
            model_name='teaching',
            name='prerequisite',
            field=models.ForeignKey(blank=True, help_text='Lesson that must be completed before this one opens.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks', to='teachings.teaching'),
        ),
        migrations.AddField(
            model_name='teachingseries',
            name='category',
            field=models.CharField(choices=[('awareness', 'Awareness & foundations'), ('practice', 'Meditation & practice'), ('communication', 'Communication & relationships'), ('other', 'Other')], default='other', max_length=16),
        ),
        migrations.AddField(
            model_name='teachingseries',
            name='facilitator',
            field=models.CharField(blank=True, default='Dr. Baffour Jan', max_length=255),
        ),
        migrations.AddField(
            model_name='teachingseries',
            name='is_recommended',
            field=models.BooleanField(default=False, help_text='Eligible for the Recommended for You row.'),
        ),
        migrations.AddField(
            model_name='teachingseries',
            name='recommendation_reason',
            field=models.CharField(blank=True, help_text='Shown verbatim, e.g. "Continue your learning path".', max_length=120),
        ),
        migrations.CreateModel(
            name='TeachingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='teachings.teachingseries')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='teaching',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachings', to='teachings.teachingmodule'),
        ),
        migrations.AddConstraint(
            model_name='teachingmodule',
            constraint=models.UniqueConstraint(fields=('series', 'title'), name='uniq_module_title_in_series'),
        ),
            migrations.RunPython(seed_lesson_type, noop),
    ]
