# Generated by Django 6.0.3 on 2026-09-20 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_contact_centre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('morning', 'Morning'), ('breathing', 'Breathing'), ('reflection', 'Evening / Reflection'), ('general', 'General')], default='general', max_length=12)),
                ('minutes', models.PositiveSmallIntegerField(default=10)),
                ('audience', models.CharField(choices=[('public', 'Public (free intro)'), ('members', 'Members & students'), ('students', 'Students only')], default='members', max_length=10)),
                ('audio_file', models.FileField(blank=True, help_text='Guided audio hosted on R2.', upload_to='practices/audio/')),
                ('audio_url', models.URLField(blank=True, help_text='External audio URL (used when no file).')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PracticeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('minutes', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_logs', to='members.contact')),
                ('practice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='practices.practice')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['contact', 'date'], name='practices_p_contact_37c129_idx')],
            },
        ),
    ]
