# Generated by Django 6.0.3 on 2026-10-04 16:06

from django.db import migrations, models


def members_become_students(apps, schema_editor):
    """Move the retired 'members' tier onto 'students'.

    Not cosmetic. Once 'members' is no longer a valid choice the
    API filters on ['public', 'students'], so a row left on the old
    value would not become public — it would stop being returned at
    all, and the content would simply vanish.
    """
    apps.get_model('practices', 'Practice').objects.filter(
        audience='members').update(audience='students')


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0001_initial'),
    ]

    operations = [
        # Data first: the field keeps its max_length, so this is a
        # pure value move and safe to run before the choices change.
        migrations.RunPython(members_become_students,
                             migrations.RunPython.noop),
        migrations.AlterField(
            model_name='practice',
            name='audience',
            field=models.CharField(choices=[('public', 'Public (free intro)'), ('students', 'Signed-in students only')], default='students', max_length=10),
        ),
    ]
