# Generated by Django 6.0.3 on 2026-09-20 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_contact_centre'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('live', 'Live session'), ('practice', 'Group practice'), ('gathering', 'Gathering / other')], default='gathering', max_length=12)),
                ('starts_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('venue', models.CharField(blank=True, help_text='Physical venue; leave blank for Online.', max_length=255)),
                ('audience', models.CharField(choices=[('public', 'Public (everyone)'), ('members', 'Members & students'), ('students', 'Students only')], default='public', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='activities.activity')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_reminders', to='members.contact')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='programs.program')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('activity__isnull', False)), fields=('contact', 'activity'), name='uniq_activity_reminder'), models.UniqueConstraint(condition=models.Q(('program__isnull', False)), fields=('contact', 'program'), name='uniq_program_reminder')],
            },
        ),
    ]
