# Generated by Django 6.0.3 on 2026-09-30 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('members', '0003_contact_centre'),
        ('staff_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilitator_name', models.CharField(blank=True, help_text='Used when the facilitator is not JCF staff.', max_length=255)),
                ('facilitator_role', models.CharField(blank=True, max_length=255)),
                ('facilitator_portrait', models.ImageField(blank=True, help_text='An approved portrait. Without one the app shows initials.', upload_to='live/facilitators/')),
                ('poster', models.ImageField(blank=True, upload_to='live/posters/')),
                ('full_description', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, default='English', max_length=40)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('playback_url', models.URLField(blank=True, help_text='HTTPS HLS (or DASH) playback URL.')),
                ('playback_type', models.CharField(choices=[('hls', 'HLS'), ('dash', 'DASH'), ('progressive', 'Progressive MP4')], default='hls', max_length=12)),
                ('captions_url', models.URLField(blank=True, help_text='WebVTT track.')),
                ('dvr_enabled', models.BooleanField(default=False, help_text='Allow rewinding within the live window.')),
                ('low_latency', models.BooleanField(default=False)),
                ('replay_url', models.URLField(blank=True)),
                ('replay_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('replay_status', models.CharField(choices=[('none', 'No replay'), ('processing', 'Processing'), ('available', 'Available')], default='none', max_length=12)),
                ('replay_available_until', models.DateTimeField(blank=True, null=True)),
                ('chat_enabled', models.BooleanField(default=True)),
                ('chat_visible_to_guests', models.BooleanField(default=True)),
                ('chat_requires_auth_to_post', models.BooleanField(default=True)),
                ('slow_mode_seconds', models.PositiveSmallIntegerField(default=0)),
                ('max_message_length', models.PositiveSmallIntegerField(default=300)),
                ('access_tier', models.CharField(choices=[('public', 'Public'), ('members', 'Members & students'), ('students', 'Students only')], default='public', max_length=10)),
                ('cancelled', models.BooleanField(default=False)),
                ('rescheduled_note', models.CharField(blank=True, max_length=255)),
                ('viewer_count_visible', models.BooleanField(default=True)),
                ('sharing_allowed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_session', to='activities.activity')),
                ('facilitator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_sessions', to='staff_mgmt.worker')),
            ],
        ),
        migrations.CreateModel(
            name='LiveReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('appreciate', 'Appreciation'), ('thanks', 'Thank you'), ('insight', 'Insightful')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_reactions', to='members.contact')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='activities.livesession')),
            ],
        ),
        migrations.CreateModel(
            name='LiveChatMute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_chat_mutes', to='members.contact')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutes', to='activities.livesession')),
            ],
        ),
        migrations.CreateModel(
            name='LiveChatBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_chat_blocked_by', to='members.contact')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_chat_blocks', to='members.contact')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('contact', 'blocked'), name='uniq_live_chat_block')],
            },
        ),
        migrations.CreateModel(
            name='LiveSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_saves', to='members.contact')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='activities.livesession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'contact'), name='uniq_live_save')],
            },
        ),
        migrations.CreateModel(
            name='LiveChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('participant', 'Participant'), ('facilitator', 'Facilitator'), ('moderator', 'Moderator'), ('system', 'System')], default='participant', max_length=12)),
                ('text', models.TextField()),
                ('pinned', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('reported_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_chat_messages', to='members.contact')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='activities.livesession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['session', 'id'], name='activities__session_466480_idx')],
            },
        ),
        migrations.CreateModel(
            name='LiveViewerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_viewer_sessions', to='members.contact')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_sessions', to='activities.livesession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'key'), name='uniq_live_viewer_session')],
            },
        ),
    ]
