# Generated by Django 6.0.3 on 2026-09-30 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_livesession_livereaction_livechatmute_livechatblock_and_more'),
        ('members', '0003_contact_centre'),
        ('staff_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('waitlisted', 'Waitlisted'), ('cancelled', 'Cancelled')], default='registered', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivitySave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_format',
            field=models.CharField(choices=[('online', 'Online'), ('in_person', 'In person'), ('hybrid', 'Hybrid (both)')], default='in_person', max_length=12, verbose_name='format'),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('satsang', 'Satsang'), ('meditation', 'Guided meditation'), ('workshop', 'Workshop'), ('teaching', 'Teaching'), ('retreat', 'Retreat'), ('practice', 'Group practice'), ('community', 'Community gathering'), ('other', 'Other')], default='other', max_length=16),
        ),
        migrations.AddField(
            model_name='activity',
            name='all_day',
            field=models.BooleanField(default=False, help_text='Show a date without a clock time (retreats, festivals).'),
        ),
        migrations.AddField(
            model_name='activity',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Blank means unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='activity',
            name='country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='activity',
            name='external_registration_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='facilitator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='staff_mgmt.worker'),
        ),
        migrations.AddField(
            model_name='activity',
            name='facilitator_name',
            field=models.CharField(blank=True, help_text='Used when the facilitator is not JCF staff.', max_length=255),
        ),
        migrations.AddField(
            model_name='activity',
            name='featured_blurb',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activity',
            name='fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Blank means free.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='fee_currency',
            field=models.CharField(blank=True, default='GHS', max_length=3),
        ),
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, upload_to='activities/'),
        ),
        migrations.AddField(
            model_name='activity',
            name='image_key',
            field=models.CharField(blank=True, help_text='Packaged artwork the app falls back to, e.g. "retreat".', max_length=64),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Candidate for the banner above the list. The server picks the soonest featured activity the caller may see.'),
        ),
        migrations.AddField(
            model_name='activity',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=40),
        ),
        migrations.AddField(
            model_name='activity',
            name='online_platform',
            field=models.CharField(blank=True, help_text='Zoom, JCF Live, YouTube … shown on online activities.', max_length=80),
        ),
        migrations.AddField(
            model_name='activity',
            name='registration_closes_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='registration_opens_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='registration_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='rescheduled_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activity',
            name='waitlist_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['starts_at', 'id'], name='activities__starts__08748f_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['is_active', 'starts_at'], name='activities__is_acti_56791d_idx'),
        ),
        migrations.AddField(
            model_name='activityregistration',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='activityregistration',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_registrations', to='members.contact'),
        ),
        migrations.AddField(
            model_name='activitysave',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='activities.activity'),
        ),
        migrations.AddField(
            model_name='activitysave',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_saves', to='members.contact'),
        ),
        migrations.AddConstraint(
            model_name='activityregistration',
            constraint=models.UniqueConstraint(fields=('contact', 'activity'), name='uniq_activity_signup'),
        ),
        migrations.AddConstraint(
            model_name='activitysave',
            constraint=models.UniqueConstraint(fields=('contact', 'activity'), name='uniq_activity_save'),
        ),
    ]
