# Generated by Django 6.0.3 on 2026-09-30 03:11

from datetime import timedelta

from django.db import migrations, models


def backfill_ends_at(apps, schema_editor):
    """Existing rows have never been through save(), so fill them here."""
    Activity = apps.get_model('activities', 'Activity')
    for activity in Activity.objects.filter(ends_at__isnull=True).iterator():
        Activity.objects.filter(pk=activity.pk).update(
            ends_at=activity.starts_at
            + timedelta(minutes=activity.duration_minutes))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activityregistration_activitysave_and_more'),
        ('staff_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='ends_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Derived from starts_at + duration_minutes on save.', null=True),
        ),
        migrations.RunPython(backfill_ends_at, noop),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['ends_at'], name='activities__ends_at_373372_idx'),
        ),
    ]
