# Generated by Django 6.0.3 on 2026-10-04 16:06

from django.db import migrations, models


def members_become_students(apps, schema_editor):
    """Move the retired 'members' tier onto 'students'.

    Not cosmetic. Once 'members' is no longer a valid choice the
    API filters on ['public', 'students'], so a row left on the old
    value would not become public — it would stop being returned at
    all, and the content would simply vanish.
    """
    apps.get_model('activities', 'Activity').objects.filter(
        audience='members').update(audience='students')
    apps.get_model('activities', 'LiveSession').objects.filter(
        access_tier='members').update(access_tier='students')


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activity_ends_at'),
    ]

    operations = [
        # Data first: the field keeps its max_length, so this is a
        # pure value move and safe to run before the choices change.
        migrations.RunPython(members_become_students,
                             migrations.RunPython.noop),
        migrations.AlterField(
            model_name='activity',
            name='audience',
            field=models.CharField(choices=[('public', 'Public (everyone)'), ('students', 'Signed-in students only')], default='public', max_length=10),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='access_tier',
            field=models.CharField(choices=[('public', 'Public'), ('students', 'Signed-in students only')], default='public', max_length=10),
        ),
    ]
