# Generated by Django 6.0.3 on 2026-03-15 00:53

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('location', models.CharField(help_text='City name, e.g. Accra', max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('country', models.CharField(default='Ghana', max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='centres/')),
                ('description', models.TextField()),
                ('leader_name', models.CharField(max_length=255)),
                ('leader_title', models.CharField(help_text='e.g. Centre Director', max_length=255)),
                ('leader_avatar', models.ImageField(blank=True, upload_to='centres/leaders/')),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('member_count', models.PositiveIntegerField(default=0, help_text='Approximate number of members.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
