# Generated by Django 6.0.3 on 2026-04-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centre',
            name='member_count',
        ),
        migrations.AddField(
            model_name='centre',
            name='telegram_link',
            field=models.URLField(blank=True, help_text='Telegram group invite link.'),
        ),
        migrations.AddField(
            model_name='centre',
            name='whatsapp_link',
            field=models.URLField(blank=True, help_text='WhatsApp group invite link.'),
        ),
    ]
