# Generated by Django 6.0.3 on 2026-03-15 00:53

import django.db.models.deletion
import phonenumber_field.modelfields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CauseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'cause categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(help_text='Short summary for listing cards.')),
                ('content', tinymce.models.HTMLField(help_text='Full cause details (rich text).')),
                ('image', models.ImageField(blank=True, upload_to='causes/')),
                ('gallery', models.JSONField(blank=True, default=list, help_text='List of additional image paths.')),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='causes', to='causes.causecategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=255)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('donor_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('online', 'Online (Paystack)'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='completed', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Bank or mobile money reference.', max_length=100)),
                ('paystack_reference', models.CharField(blank=True, help_text='Paystack transaction reference.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('donated_at', models.DateTimeField(help_text='When the donation was made.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cause', models.ForeignKey(blank=True, help_text='Leave blank for general donations.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='causes.cause')),
            ],
            options={
                'ordering': ['-donated_at'],
            },
        ),
    ]
