# Generated by Django 6.0.3 on 2026-03-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='content',
            field=models.TextField(help_text='Full cause details (rich text).'),
        ),
    ]
