# Generated by Django 6.0.3 on 2026-04-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='impact_statement',
            field=models.CharField(blank=True, help_text='Short impact line for ongoing causes (e.g. "Reaching seekers across the world").', max_length=255),
        ),
        migrations.AddField(
            model_name='cause',
            name='type',
            field=models.CharField(choices=[('specific', 'Specific (has a funding goal)'), ('ongoing', 'Ongoing (no fixed goal)')], default='specific', help_text='Specific causes show a progress bar; ongoing causes focus on impact.', max_length=10),
        ),
        migrations.AlterField(
            model_name='cause',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Set to 0 for ongoing causes.', max_digits=12),
        ),
    ]
