# Generated by Django 6.0.3 on 2026-06-28 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0002_cause_impact_statement_cause_type_and_more'),
        ('members', '0003_contact_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Linked member, if donated in-app while logged in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='members.contact'),
        ),
    ]
