# Generated by Django 6.0.3 on 2026-09-20 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
        ('teachings', '0002_teachingseries_alter_teaching_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInspiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The day this inspiration is shown.', unique=True)),
                ('quote', models.TextField()),
                ('author', models.CharField(default='Dr. Baffour Jan', max_length=255)),
                ('reflection', models.TextField(blank=True, help_text='A short reflection prompt shown under the quote.')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_teaching', models.ForeignKey(blank=True, help_text='Optional teaching linked from the inspiration page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspirations', to='teachings.teaching')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
