# Generated by Django 6.0.3 on 2026-09-20 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_dailyinspiration'),
        ('members', '0003_contact_centre'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='engagement.announcement')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reads', to='members.contact')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('contact', 'announcement'), name='uniq_announcement_read')],
            },
        ),
    ]
