# Generated by Django 6.0.3 on 2026-09-30 01:09

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def backfill_slugs(apps, schema_editor):
    """Existing inspirations predate the slug, so give each one a stable
    value before the unique constraint lands."""
    Inspiration = apps.get_model('engagement', 'DailyInspiration')
    for row in Inspiration.objects.all():
        base = slugify(row.title or row.quote)[:200] or 'inspiration'
        row.slug = f'{base}-{row.date:%Y-%m-%d}'
        row.save(update_fields=['slug'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0003_announcementread'),
        ('members', '0003_contact_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyinspiration',
            name='audio_duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyinspiration',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='inspirations/audio/'),
        ),
        migrations.AddField(
            model_name='dailyinspiration',
            name='audio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='dailyinspiration',
            name='category',
            field=models.CharField(blank=True, default='Awareness', max_length=80),
        ),
        migrations.AddField(
            model_name='dailyinspiration',
            name='hero_alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dailyinspiration',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='inspirations/'),
        ),
        migrations.AddField(
            model_name='dailyinspiration',
            name='prompt_guidance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailyinspiration',
            name='prompt_question',
            field=models.TextField(blank=True, help_text='The "Pause and Reflect" question.'),
        ),
        migrations.AddField(
            model_name='dailyinspiration',
            name='share_excerpt',
            field=models.TextField(blank=True, help_text='Short line used on share cards; falls back to the quote.'),
        ),
        migrations.AddField(
            model_name='dailyinspiration',
            name='sharing_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dailyinspiration',
            name='slug',
            # db_index=False here: the unique AlterField below creates the
            # index, and SlugField's implicit one would collide with it.
            field=models.SlugField(
                blank=True, max_length=255, default='', db_index=False),
        ),
        migrations.AddField(
            model_name='dailyinspiration',
            name='title',
            field=models.CharField(blank=True, help_text='Headline for the detail screen; falls back to the quote.', max_length=255),
        ),
        migrations.CreateModel(
            name='InspirationBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('paragraph', 'Paragraph'), ('heading', 'Heading'), ('subheading', 'Subheading'), ('pull_quote', 'Pull quote'), ('image', 'Image'), ('bullet_list', 'Bullet list'), ('numbered_list', 'Numbered list'), ('divider', 'Divider')], default='paragraph', max_length=16)),
                ('text', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, help_text='Attribution for a pull quote.', max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='inspirations/body/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('items', models.JSONField(blank=True, default=list, help_text='List entries, for list blocks.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('inspiration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='engagement.dailyinspiration')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InspirationReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reflected_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspiration_reflections', to='members.contact')),
                ('inspiration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='engagement.dailyinspiration')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('contact', 'inspiration'), name='uniq_inspiration_reflection')],
            },
        ),
        migrations.CreateModel(
            name='InspirationSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspiration_saves', to='members.contact')),
                ('inspiration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='engagement.dailyinspiration')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('contact', 'inspiration'), name='uniq_inspiration_save')],
            },
        ),
        migrations.RunPython(backfill_slugs, noop),
        migrations.AlterField(
            model_name='dailyinspiration',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
