# Generated by Django 6.0.3 on 2026-09-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0004_dailyinspiration_audio_duration_seconds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('terms', 'Terms of Use'), ('privacy', 'Privacy Policy')], max_length=10)),
                ('version', models.CharField(help_text='e.g. "2026-09" or "1.2". Acceptance is recorded against this exact value.', max_length=20)),
                ('language', models.CharField(default='en', help_text='Language code. English is the fallback when a translation has not been authored.', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Markdown or plain text.')),
                ('is_published', models.BooleanField(default=False)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', '-effective_from', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'version', 'language'), name='uniq_legal_version_per_language')],
            },
        ),
    ]
