# Generated by Django 6.0.3 on 2026-10-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0005_legaldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='app_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='locale',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='permission_status',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='registration_key',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='timezone',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
