# Generated by Django 6.0.3 on 2026-10-07 19:42

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('members', '0004_contact_day_of_birth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('day_of_birth', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('profession', models.CharField(max_length=255)),
                ('hometown', models.CharField(max_length=255, verbose_name='Home town / region')),
                ('religion', models.CharField(max_length=255)),
                ('residence', models.CharField(max_length=255, verbose_name='Current residence')),
                ('heard_from', models.CharField(choices=[('friend', 'A friend or family member'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('radio_tv', 'Radio or TV'), ('website', 'The Foundation website'), ('centre', 'A JCF centre or event'), ('other', 'Somewhere else')], max_length=20)),
                ('heard_detail', models.CharField(blank=True, max_length=255)),
                ('preferred_mode', models.CharField(blank=True, choices=[('Onsite', 'In person'), ('Remote', 'Remotely (phone or video)')], max_length=10)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('booked', 'Booked'), ('closed', 'Closed')], default='new', max_length=10)),
                ('created_contact', models.BooleanField(default=False, help_text='The form added this person to contacts.')),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='consultations.consultation')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='members.contact')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
