# Generated by Django 6.0.3 on 2026-10-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_booking_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='heard_from',
            field=models.CharField(blank=True, choices=[('friend', 'A friend or family member'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('radio_tv', 'Radio or TV'), ('website', 'The Foundation website'), ('centre', 'A JCF centre or event'), ('other', 'Somewhere else')], max_length=20),
        ),
    ]
