# Generated by Django 6.0.3 on 2026-10-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_optional_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the date was last texted to the contact.', null=True),
        ),
    ]
