# Generated by Django 6.0.3 on 2026-08-23 10:27

import django.db.models.deletion
import django.utils.timezone
import innerspace.cuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.CharField(default=innerspace.cuid.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('FREE', 'Free'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELED', 'Canceled')], db_column='status', max_length=20)),
                ('started_at', models.DateTimeField(db_column='startedAt')),
                ('expires_at', models.DateTimeField(blank=True, db_column='expiresAt', null=True)),
                ('provider', models.CharField(blank=True, choices=[('STRIPE', 'Stripe'), ('PAYSTACK', 'Paystack'), ('FLUTTERWAVE', 'Flutterwave'), ('CASH', 'Cash (in person)')], db_column='provider', max_length=20, null=True)),
                ('provider_ref', models.CharField(blank=True, db_column='providerRef', max_length=255, null=True)),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_column='updatedAt', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Membership',
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(default=innerspace.cuid.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('STRIPE', 'Stripe'), ('PAYSTACK', 'Paystack'), ('FLUTTERWAVE', 'Flutterwave'), ('CASH', 'Cash (in person)')], db_column='provider', max_length=20)),
                ('provider_ref', models.CharField(db_column='providerRef', max_length=255)),
                ('amount', models.DecimalField(db_column='amount', decimal_places=30, max_digits=65)),
                ('currency', models.CharField(db_column='currency', max_length=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_column='status', max_length=20)),
                ('created_at', models.DateTimeField(db_column='createdAt', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Payment',
                'ordering': ['-created_at'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(default=innerspace.cuid.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=254, null=True, unique=True)),
                ('email_verified', models.DateTimeField(blank=True, db_column='email_verified', null=True)),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=32, null=True, unique=True)),
                ('phone_verified', models.DateTimeField(blank=True, db_column='phone_verified', null=True)),
                ('first_name', models.CharField(blank=True, db_column='first_name', max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, db_column='last_name', max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_column='name', max_length=255, null=True)),
                ('image', models.TextField(blank=True, db_column='image', null=True)),
                ('access_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], db_column='accessLevel', default='INTERMEDIATE', max_length=20)),
                ('country_code', models.CharField(blank=True, db_column='country_code', max_length=8, null=True)),
                ('country', models.CharField(blank=True, db_column='country', max_length=255, null=True)),
                ('has_completed_onboarding', models.BooleanField(db_column='has_completed_onboarding', default=False)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_column='updated_at', default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Innerspace student',
                'db_table': 'users',
                'ordering': ['-created_at'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccessGrantLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=32)),
                ('student_email', models.EmailField(blank=True, max_length=254)),
                ('action', models.CharField(choices=[('grant', 'Granted access'), ('extend', 'Extended access'), ('revoke', 'Revoked access'), ('reactivate', 'Reactivated access')], max_length=20)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('receipt_ref', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='innerspace_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'access grant log entry',
                'verbose_name_plural': 'access grant log',
                'ordering': ['-created_at'],
                'permissions': [('manage_innerspace_access', 'Can grant, extend and revoke Innerspace access')],
            },
        ),
    ]
