# Generated by Django 6.0.3 on 2026-08-27 00:30

import django.utils.timezone
import innerspace.cuid
import innerspace.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innerspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.CharField(default=innerspace.cuid.cuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('requested_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], db_column='requested_level', max_length=20)),
                ('current_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], db_column='current_level', help_text='The level the student held when they asked.', max_length=20)),
                ('course_id', models.CharField(blank=True, db_column='course_id', max_length=32, null=True)),
                ('course_slug', models.CharField(blank=True, db_column='course_slug', max_length=255, null=True)),
                ('message', models.TextField(blank=True, db_column='message', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('CANCELED', 'Canceled')], db_column='status', default='PENDING', max_length=20)),
                ('reviewed_at', innerspace.fields.PrismaDateTimeField(blank=True, db_column='reviewed_at', null=True)),
                ('reviewed_by', models.CharField(blank=True, db_column='reviewed_by', max_length=255, null=True)),
                ('review_note', models.TextField(blank=True, db_column='review_note', null=True)),
                ('created_at', innerspace.fields.PrismaDateTimeField(db_column='created_at', default=django.utils.timezone.now)),
                ('updated_at', innerspace.fields.PrismaDateTimeField(db_column='updated_at', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'access_requests',
                'ordering': ['created_at'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='accessgrantlog',
            name='new_level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='accessgrantlog',
            name='previous_level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='accessgrantlog',
            name='action',
            field=models.CharField(choices=[('grant', 'Granted access'), ('extend', 'Extended access'), ('revoke', 'Revoked access'), ('reactivate', 'Reactivated access'), ('level_grant', 'Raised access level'), ('level_decline', 'Declined level request')], max_length=20),
        ),
    ]
