# Generated by Django 6.0.3 on 2026-10-07 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innerspace', '0002_accessrequest_accessgrantlog_new_level_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessRequest',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
