# Generated by Django 6.0.3 on 2026-06-28 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_contact_centre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('year', models.PositiveIntegerField(help_text='Edition year, used in the registration reference.')),
                ('description', models.TextField(blank=True)),
                ('audience', models.CharField(choices=[('public', 'Public (everyone)'), ('members', 'Members & students only'), ('students', 'Students only')], default='public', max_length=10)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='programs/')),
                ('registration_opens_at', models.DateTimeField(blank=True, null=True)),
                ('registration_closes_at', models.DateTimeField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Max registrations (blank = unlimited).', null=True)),
                ('requires_payment', models.BooleanField(default=False)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('form_schema', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CostLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(choices=[('flat', 'Flat (once per registration)'), ('per_person', 'Per person')], default='flat', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_line_items', to='programs.program')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AccommodationTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price_per_person', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_rooms', models.PositiveIntegerField(default=0)),
                ('rooms_confirmed', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_tiers', to='programs.program')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=40, unique=True)),
                ('quantity', models.PositiveSmallIntegerField(default=1, help_text='Number of people in this registration.')),
                ('answers', models.JSONField(blank=True, default=dict, help_text='Responses to the program form_schema.')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('paystack_reference', models.CharField(blank=True, max_length=100)),
                ('qr', models.ImageField(blank=True, upload_to='programs/qr/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('accommodation_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='programs.accommodationtier')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='members.contact')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='programs.program')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
