# Generated by Django 6.0.3 on 2026-09-29 20:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_contact_centre'),
        ('practices', '0001_initial'),
        ('programs', '0001_initial'),
        ('staff_mgmt', '0001_initial'),
        ('teachings', '0003_teaching_author_teaching_view_count_teachingprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort', models.CharField(blank=True, help_text='e.g. "Cohort 3" or "January intake".', max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('expired', 'Access expired'), ('suspended', 'Suspended')], default='active', max_length=12)),
                ('is_primary', models.BooleanField(default=False, help_text='Shown in the app hero when a student has several.')),
                ('access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='members.contact')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='programs.program')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolments', to='teachings.teachingseries')),
            ],
            options={
                'ordering': ['-is_primary', '-last_accessed_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mentorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(blank=True, help_text='e.g. "Weekdays, 9am - 5pm GMT".', max_length=255)),
                ('next_check_in_at', models.DateTimeField(blank=True, null=True)),
                ('messaging_enabled', models.BooleanField(default=False)),
                ('booking_enabled', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentees', to='staff_mgmt.worker')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship', to='members.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('required_progress', models.PositiveSmallIntegerField(default=100, help_text='Programme completion %% needed to achieve it.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='programs.program')),
            ],
            options={
                'ordering': ['order', 'required_progress'],
            },
        ),
        migrations.CreateModel(
            name='PracticeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('required', models.BooleanField(default=True)),
                ('excused', models.BooleanField(default=False)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_assignments', to='members.contact')),
                ('enrolment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice_assignments', to='studies.enrolment')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='practices.practice')),
            ],
            options={
                'ordering': ['due_at', '-assigned_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='enrolment',
            constraint=models.UniqueConstraint(fields=('contact', 'program'), name='uniq_enrolment'),
        ),
    ]
