# Generated by Django 6.0.3 on 2026-04-12 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0002_remove_centre_member_count_centre_telegram_link_and_more'),
        ('members', '0002_rename_is_initiate_to_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='centre',
            field=models.ForeignKey(blank=True, help_text='Centre this contact belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='centres.centre'),
        ),
    ]
