# Generated by Django 6.0.3 on 2026-10-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_contact_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='day_of_birth',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], help_text='Only needed when the date of birth is not known.', max_length=10),
        ),
    ]
